# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{Markaby}
  s.version = "0.6.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["_why", "Tim Fletcher", "John Barton", "spox", "smtlaissezfaire"]
  s.date = %q{2009-08-23}
  s.description = %q{Tim Fletcher and _why's ruby driven HTML templating system}
  s.email = %q{jrbarton@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG",
     "Markaby.gemspec",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "init.rb",
     "lib/markaby.rb",
     "lib/markaby/builder.rb",
     "lib/markaby/builder_tags.rb",
     "lib/markaby/cssproxy.rb",
     "lib/markaby/kernel_method.rb",
     "lib/markaby/rails.rb",
     "lib/markaby/tags.rb",
     "lib/markaby/template.rb",
     "test/rails/markaby/_monkeys.mab",
     "test/rails/markaby/broken.mab",
     "test/rails/markaby/create.mab",
     "test/rails/markaby/index.mab",
     "test/rails/monkeys.html",
     "test/rails/test_helper.rb",
     "test/rails/test_preamble.rb",
     "test/rails_test.rb",
     "test/test_builder.rb",
     "test/test_css_proxy.rb",
     "test/test_helper.rb",
     "test/test_markaby.rb"
  ]
  s.has_rdoc = true
  s.homepage = %q{http://joho.github.com/markaby/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.1}
  s.summary = %q{Markup as Ruby, write HTML in your native Ruby tongue}
  s.test_files = [
    "test/rails/test_helper.rb",
     "test/rails/test_preamble.rb",
     "test/rails_test.rb",
     "test/test_builder.rb",
     "test/test_css_proxy.rb",
     "test/test_helper.rb",
     "test/test_markaby.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 2

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<builder>, [">= 2.0.0"])
    else
      s.add_dependency(%q<builder>, [">= 2.0.0"])
    end
  else
    s.add_dependency(%q<builder>, [">= 2.0.0"])
  end
end
